import React from 'react';

interface TermsAndConditionsModalProps {
    onClose: () => void;
}

export const TermsAndConditionsModal: React.FC<TermsAndConditionsModalProps> = ({ onClose }) => {
    return (
        <div className="text-slate-300">
            <h2 id="modal-title" className="text-2xl font-bold text-white mb-6">
                Términos y condiciones de uso
            </h2>
            <div className="space-y-4 text-sm max-h-[60vh] pr-4 -mr-4 overflow-y-auto">
                <h3 className="text-lg font-semibold text-slate-100 mt-4">1. DATOS IDENTIFICATIVOS</h3>
                <p>El presente Aviso Legal regula el uso del servicio de la aplicación informándole en cumplimiento de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico, de los siguientes extremos: GRUPO INFINITY, S.COOP.AND (en adelante el prestador), con domicilio a estos efectos en Urb. Parque Botánico, E316, 29679, Benahavís, Málaga con NIF F16945909. Correo electrónico de contacto: info@melenamarketing.com.</p>

                <h3 className="text-lg font-semibold text-slate-100 mt-4">2. USUARIOS</h3>
                <p>El acceso y/o uso de este portal de EL PRESTADOR atribuye la condición de USUARIO, que acepta, desde dicho acceso y/o uso, las Condiciones Generales de Uso aquí reflejadas. Las citadas Condiciones serán de aplicación independientemente de las Condiciones Generales de Contratación que en su caso resulten de obligado cumplimiento.</p>

                <h3 className="text-lg font-semibold text-slate-100 mt-4">3. USO DEL PORTAL</h3>
                <p>Gespadel.app proporciona el acceso a multitud de informaciones, servicios, programas o datos (en adelante, “los contenidos”) en Internet pertenecientes a EL PRESTADOR o a sus licenciantes a los que el USUARIO pueda tener acceso. El USUARIO asume la responsabilidad del uso del portal. Dicha responsabilidad se extiende al registro que fuese necesario para acceder a determinados servicios o contenidos. En dicho registro el USUARIO será responsable de aportar información veraz y lícita. Como consecuencia de este registro, al USUARIO se le puede proporcionar una contraseña de la que será responsable, comprometiéndose a hacer un uso diligente y confidencial de la misma. El USUARIO se compromete a hacer un uso adecuado de los contenidos y servicios (como por ejemplo servicios de chat, foros de discusión o grupos de noticias) que EL PRESTADOR ofrece a través de su portal y con carácter enunciativo pero no limitativo, a no emplearlos para (i) incurrir en actividades ilícitas, ilegales o contrarias a la buena fe y al orden público; (ii) difundir contenidos o propaganda de carácter racista, xenófobo, pornográfico-ilegal, de apología del terrorismo o atentatorio contra los derechos humanos; (iii) provocar daños en los sistemas físicos y lógicos de EL PRESTADOR , de sus proveedores o de terceras personas, introducir o difundir en la red virus informáticos o cualesquiera otros sistemas físicos o lógicos que sean susceptibles de provocar los daños anteriormente mencionados; (iv) intentar acceder y, en su caso, utilizar las cuentas de correo electrónico de otros usuarios y modificar o manipular sus mensajes. EL PRESTADOR se reserva el derecho de retirar todos aquellos comentarios y aportaciones que vulneren el respeto a la dignidad de la persona, que sean discriminatorios, xenófobos, racistas, pornográficos, que atenten contra la juventud o la infancia, el orden o la seguridad pública o que, a su juicio, no resultaran adecuados para su publicación. En cualquier caso, EL PRESTADOR no será responsable de las opiniones vertidas por los usuarios a través de los foros, chats, u otras herramientas de participación.</p>

                <h3 className="text-lg font-semibold text-slate-100 mt-4">4. PROPIEDAD INTELECTUAL E INDUSTRIAL</h3>
                <h4 className="text-md font-semibold text-slate-200 mt-2">Titularidad de los derechos</h4>
                <p>EL PRESTADOR, como titular de la aplicación, por sí o como cesionaria, ostenta todos los derechos de propiedad intelectual e industrial de la presente aplicación, así como de los elementos contenidos en el mismo. Estos incluyen, entre otros, a título enunciativo y no limitativo: el diseño gráfico, los logotipos, las combinaciones de colores, la estructura y diseño, las imágenes, sonidos, audios, vídeos, software y textos, la selección de materiales utilizados y los programas de ordenador necesarios para su funcionamiento, acceso y uso. Estos elementos son titularidad de EL PRESTADOR o de sus licenciantes, y están protegidos por la legislación nacional e internacional en materia de propiedad intelectual e industrial.</p>
                <h4 className="text-md font-semibold text-slate-200 mt-2">Usos permitidos y restricciones</h4>
                <p>Se permite a los usuarios visualizar, imprimir, copiar y almacenar los elementos de esta aplicación, siempre que sea única y exclusivamente para su uso personal y privado, y con la condición de que no se utilicen con fines comerciales. Quedan expresamente prohibidas, sin la autorización previa y por escrito de EL PRESTADOR, la reproducción, distribución, comunicación pública, incluida su modalidad de puesta a disposición, de la totalidad o parte de los contenidos de la aplicación. También está prohibida la alteración o manipulación de cualquier contenido, dispositivo de protección o sistema de seguridad instalado en la aplicación, así como el uso de los contenidos para fines ilegales, lesivos de los derechos de terceros o contrarios al orden público.</p>
                <p>El usuario se compromete a no retirar, suprimir, alterar, manipular ni en modo alguno modificar aquellas notas, leyendas, indicaciones o símbolos que el legítimo titular de los derechos incorpore a sus propiedades en materia de propiedad intelectual o industrial (como, por ejemplo, copyright, ©, ® y ™, etc.). Asimismo, se compromete a no alterar ni eliminar los dispositivos técnicos de protección o identificación que puedan contener los contenidos (como, por ejemplo, marcas de agua, huellas digitales, etc.).</p>
                <p>Las restricciones anteriores no limitan el ejercicio de los derechos de cita, crítica o uso educativo reconocido en la legislación vigente en materia de propiedad intelectual.</p>
                <h4 className="text-md font-semibold text-slate-200 mt-2">Contenidos generados por los usuarios</h4>
                <p>La aplicación permite a los usuarios subir y compartir contenidos, como imágenes, textos o cualquier otro material (en adelante, "CONTENIDOS DE USUARIO"). Los usuarios garantizan que son los únicos titulares de los derechos de propiedad intelectual sobre los contenidos que suben, o que cuentan con las licencias y autorizaciones necesarias para utilizarlos y compartirlos. Asimismo, garantizan que los contenidos no infringen derechos de terceros, incluidos, entre otros, derechos de propiedad intelectual e industrial, derechos al honor, a la intimidad o a la propia imagen. EL PRESTADOR no se hace responsable de los CONTENIDOS DE USUARIO publicados en la aplicación, siendo los usuarios únicos responsables de los mismos.</p>
                <p>EL PRESTADOR se reserva el derecho de moderar, eliminar o no publicar los contenidos generados por los usuarios que considere inapropiados o que vulneren las presentes condiciones. Esta acción podrá realizarse sin previo aviso, especialmente cuando dichos contenidos puedan suponer un riesgo legal o un perjuicio a terceros.</p>
                <h4 className="text-md font-semibold text-slate-200 mt-2">Procedimiento de retirada de contenidos</h4>
                <p>En caso de que cualquier persona o entidad considere que algún contenido publicado en la aplicación vulnera sus derechos de propiedad intelectual, industriales o cualquier otro derecho, podrá notificarlo a EL PRESTADOR mediante un correo electrónico dirigido a info@melenamarketing.com o a través del formulario de contacto disponible en la aplicación. Dicha notificación deberá incluir la identificación del contenido que se reclama como infractor, una justificación razonable de la supuesta infracción de derechos, los datos de contacto del reclamante (nombre completo, dirección, teléfono y correo electrónico) y una declaración expresa de que la información proporcionada es veraz y de que el reclamante es titular de los derechos vulnerados o cuenta con autorización para actuar en su nombre. Tras recibir la notificación, EL PRESTADOR evaluará la reclamación y, en su caso, procederá a retirar el contenido presuntamente infractor de forma diligente.</p>
                <h4 className="text-md font-semibold text-slate-200 mt-2">Acciones legales</h4>
                <p>EL PRESTADOR se reserva el derecho de emprender las acciones legales que considere oportunas contra los usuarios que vulneren sus derechos de propiedad intelectual e industrial o los derechos de terceros mediante el uso de esta aplicación. Asimismo, cualquier infracción podrá dar lugar a reclamaciones por daños y perjuicios.</p>
                <p>El usuario se compromete a indemnizar y mantener indemne a EL PRESTADOR frente a cualquier reclamación, daño, perjuicio, pérdida o gasto (incluidos honorarios legales razonables) que se derive del uso indebido de la aplicación o de la infracción de los derechos de propiedad intelectual, industrial o de cualquier otro tipo cometida por el usuario.</p>
                <h4 className="text-md font-semibold text-slate-200 mt-2">Protección de los dispositivos técnicos</h4>
                <p>Cualquier intento de manipulación, eliminación o elusión de los dispositivos técnicos de protección incorporados en la aplicación será considerado una infracción grave de los derechos de propiedad intelectual e industrial. EL PRESTADOR podrá adoptar medidas legales contra los infractores.</p>
                
                <h3 className="text-lg font-semibold text-slate-100 mt-4">5. EXCLUSIÓN DE GARANTÍAS Y RESPONSABILIDAD</h3>
                <p>EL PRESTADOR no se hace responsable, en ningún caso, de los daños y perjuicios de cualquier naturaleza que pudieran ocasionar, a título enunciativo: errores u omisiones en los contenidos, falta de disponibilidad del portal o la transmisión de virus o programas maliciosos o lesivos en los contenidos, a pesar de haber adoptado todas las medidas tecnológicas necesarias para evitarlo.</p>
                
                <h3 className="text-lg font-semibold text-slate-100 mt-4">6. MODIFICACIONES</h3>
                <p>EL PRESTADOR se reserva el derecho de efectuar sin previo aviso las modificaciones que considere oportunas en su portal, pudiendo cambiar, suprimir o añadir tanto los contenidos y servicios que se presten a través de la misma como la forma en la que éstos aparezcan presentados o localizados en su portal.</p>
                
                <h3 className="text-lg font-semibold text-slate-100 mt-4">7. ENLACES</h3>
                <p>En el caso de que en Gespadel.app se dispusiesen enlaces o hipervínculos hacía otros sitios de Internet, EL PRESTADOR no ejercerá ningún tipo de control sobre dichos sitios y contenidos. En ningún caso EL PRESTADOR asumirá responsabilidad alguna por los contenidos de algún enlace perteneciente a un sitio web ajeno, ni garantizará la disponibilidad técnica, calidad, fiabilidad, exactitud, amplitud, veracidad, validez y constitucionalidad de cualquier material o información contenida en ninguno de dichos hipervínculos u otros sitios de Internet.Igualmente, la inclusión de estas conexiones externas no implicará ningún tipo de asociación, fusión o participación con las entidades conectadas.</p>
                
                <h3 className="text-lg font-semibold text-slate-100 mt-4">8. DERECHO DE EXCLUSIÓN</h3>
                <p>EL PRESTADOR se reserva el derecho a denegar o retirar el acceso a portal y/o los servicios ofrecidos sin necesidad de preaviso, a instancia propia o de un tercero, a aquellos usuarios que incumplan las presentes Condiciones Generales de Uso.</p>
                
                <h3 className="text-lg font-semibold text-slate-100 mt-4">9. GENERALIDADES</h3>
                <p>EL PRESTADOR perseguirá el incumplimiento de las presentes condiciones, así como cualquier utilización indebida de su portal ejerciendo todas las acciones civiles y penales que le puedan corresponder en derecho.</p>
                
                <h3 className="text-lg font-semibold text-slate-100 mt-4">10. MODIFICACIÓN DE LAS PRESENTES CONDICIONES Y DURACIÓN</h3>
                <p>EL PRESTADOR podrá modificar en cualquier momento las condiciones aquí determinadas, siendo debidamente publicadas como aquí aparecen.La vigencia de las citadas condiciones irá en función de su exposición y estarán vigentes hasta que sean modificadas por otras debidamente publicadas.</p>
                
                <h3 className="text-lg font-semibold text-slate-100 mt-4">11. LEGISLACIÓN APLICABLE Y JURISDICCIÓN</h3>
                <p>Las presentes Condiciones Generales de Uso, así como el uso de la aplicación, se regirán por la legislación española. En caso de litigio, las partes contratantes acuerdan someterse a los Jueces y Tribunales de domicilio del consumidor, siempre que el mismo esté situado en territorio español. De lo contrario, si se trata de un usuario no consumidor o de un consumidor situado fuera del territorio español, la sumisión será a los juzgados y tribunrales de la ciudad del domicilio del PRESTADOR. Asumiendo la parte que incumpla el contrato los gastos judiciales y extrajudiciales que se deriven de la reclamación incluido los gastos de abogados, procuradores, etc.Antes de acudir a la vía judicial, las partes acuerdan intentar resolver cualquier conflicto que surja en relación con estas condiciones mediante un procedimiento de mediación o arbitraje de conformidad con lo establecido en la legislación vigente. El procedimiento de mediación o arbitraje será realizado por una institución independiente acordada por ambas partes, y se llevará a cabo de manera confidencial. En caso de que no se alcance un acuerdo, las partes podrán acudir a los tribunales correspondientes.En el supuesto de que cualquier estipulación de las presentes Condiciones Generales de Uso resultara inexigible o nula en virtud de la legislación aplicable o como consecuencia de una resolución judicial o administrativa, dicha inexigibilidad o nulidad no hará que las presentes Condiciones Generales de Uso resulten inexigibles o nulas en su conjunto. En dichos casos, el PRESTADOR procederá a la modificación o sustitución de dicha estipulación por otra que sea válida y exigible y que, en la medida de lo posible, consiga el objetivo y pretensión reflejados en la estipulación original.</p>

            </div>

            <div className="flex justify-end gap-4 pt-6">
                <button type="button" onClick={onClose} className="px-6 py-2 font-semibold text-slate-300 bg-slate-700 rounded-lg hover:bg-slate-600 transition-all">
                    Cerrar
                </button>
            </div>
        </div>
    );
};
